name: Deploy Next.js Application with Postgres

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: nextjs-dashboard-postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Rename .env.example to .env
        run: mv .env.example .env

      - name: Install dependencies
        run: pnpm install

      - name: Run lint test
        run: pnpm lint

      - name: Build the application
        run: |
          pnpm dev & # Run in the background
          echo "Application is running in the background"
          sleep 30 # Optional: wait for a few seconds to ensure the server starts
